version: "3.6"
services:
  clearmlserver:
    command:
     - -c
     - "echo \"#!/bin/bash\" > /opt/clearml/all.sh && echo \"/opt/clearml/wrapper.sh webserver&\" >> /opt/clearml/all.sh && echo \"/opt/clearml/wrapper.sh fileserver&\" >> /opt/clearml/all.sh && echo \"/opt/clearml/wrapper.sh apiserver\" >> /opt/clearml/all.sh && cat /opt/clearml/all.sh && chmod +x /opt/clearml/all.sh && /opt/clearml/all.sh"
    entrypoint: /bin/bash
    container_name: clearml-server
    image: allegroai/clearml:latest
    ports:
    - 8008:8008
    - 8080:80
    - 8081:8081
    restart: unless-stopped
    volumes:
    - /opt/clearml/logs:/var/log/trains
    - /opt/clearml/data/fileserver:/mnt/fileserver
    - /opt/clearml/config:/opt/trains/config

    depends_on:
      - redis
      - mongo
      - elasticsearch
    environment:
      TRAINS_ELASTIC_SERVICE_HOST: elasticsearch
      TRAINS_ELASTIC_SERVICE_PORT: 9200
      TRAINS_MONGODB_SERVICE_HOST: mongo
      TRAINS_MONGODB_SERVICE_PORT: 27017
      TRAINS_REDIS_SERVICE_HOST: redis
      TRAINS_REDIS_SERVICE_PORT: 6379
    networks:
      - backend
  elasticsearch:
    networks:
      - backend
    container_name: clearml-elastic
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      bootstrap.memory_lock: "true"
      cluster.name: clearml
      cluster.routing.allocation.node_initial_primaries_recoveries: "500"
      cluster.routing.allocation.disk.watermark.low: 500mb
      cluster.routing.allocation.disk.watermark.high: 500mb
      cluster.routing.allocation.disk.watermark.flood_stage: 500mb
      discovery.zen.minimum_master_nodes: "1"
      discovery.type: "single-node"
      http.compression_level: "7"
      node.ingest: "true"
      node.name: clearml
      reindex.remote.whitelist: '*.*'
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: unless-stopped
    volumes:
    - /opt/clearml/data/elastic_7:/usr/share/elasticsearch/data
  mongo:
    networks:
      - backend
    container_name: clearml-mongo
    image: mongo:3.6.5
    restart: unless-stopped
    command: --setParameter internalQueryExecMaxBlockingSortBytes=196100200
    volumes:
    - /opt/clearml/data/mongo/db:/data/db
    - /opt/clearml/data/mongo/configdb:/data/configdb
  redis:
    networks:
      - backend
    container_name: clearml-redis
    image: redis:5.0
    restart: unless-stopped
    volumes:
    - /opt/clearml/data/redis:/data

networks:
  backend:
    driver: bridge
